name: Scheduled Contract Tests

on:
  schedule:
    # Run once per month on the 1st at 2 AM UTC
    - cron: '0 2 1 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  contract-tests:
    name: Scheduled Contract Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, curl, libxml, zip

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.3-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Contract Tests
        run: composer test -- --group=contract
        env:
          CI: true

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'contract-test-failure'
            });
            
            // Check if there's already an open issue for contract test failures
            if (issues.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Contract Tests Failed - TVMaze API Changes Detected',
                body: `Contract tests failed on ${new Date().toISOString()}. This may indicate changes in the TVMaze API that require updates to the client.
                
                Please check the [latest workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId}) for details.
                
                If this is a temporary issue with the TVMaze API, please close this issue. If the API has changed, please update the client accordingly.`,
                labels: ['contract-test-failure', 'bug']
              });
            }
